name: Deploy LLAMA3 to Jozu Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  actions: write
env:
  ARTIFACT_NAME: jozu-artifact
  REPOSITORY_NAME: llama3-githubactions
  TAG: latest
  USERNAME: shivaylamba

jobs:
  unpack-to-model:
    name: unpack-large-model
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install kit
        uses: jozu-ai/gh-kit-setup@v1.0.0
      - name: kit version
        shell: bash
        run: |
            kit version

      - name: unpack llama3 model to models folder
        shell: bash
        run: kit unpack jozu.ml/jozu/llama3-8b:8B-instruct-q5_0 --model -d models

      - name: upload-artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{env.ARTIFACT_NAME}}
            path: .
            overwrite: true


  push-to-jozuhub:
    name: push-to-jozu
    runs-on: ubuntu-latest
    needs: unpack-to-model
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
            name: ${{env.ARTIFACT_NAME}}

      - name: Display structure of downloaded files
        run: ls -R
      - name: install kit
        uses: jozu-ai/gh-kit-setup@v1.0.0
      - name: login-to-jozuhub
        shell: bash
        env: 
            JOZU_EMAIL: ${{secrets.JOZU_EMAIL}}
            JOZU_PASSWORD: ${{secrets.JOZU_PASSWORD}}
        run: kit login jozu.ml -u $JOZU_EMAIL -p $JOZU_PASSWORD
      - name: pack-modelkit
        shell: bash
        env:
            REPOSITORY_NAME: ${{env.REPOSITORY_NAME}}
            TAG: ${{env.TAG}}
            USERNAME: ${{env.USERNAME}}
        run: kit pack . -t jozu.ml/$USERNAME/$REPOSITORY_NAME:$TAG
      - name: push-modelkit
        shell: bash
        env:
            REPOSITORY_NAME: ${{env.REPOSITORY_NAME}}
            TAG: ${{env.TAG}}
            USERNAME: ${{env.USERNAME}}
        run: kit push jozu.ml/$USERNAME/$REPOSITORY_NAME:$TAG
